/* NFL team reference data — abbreviation, full name, and brand colors
   used to render team badges throughout the site. */
const NFL_TEAMS = {
  ARI: { name: "Arizona Cardinals",     color: "#97233F", text: "#FFFFFF" },
  ATL: { name: "Atlanta Falcons",       color: "#A71930", text: "#FFFFFF" },
  BAL: { name: "Baltimore Ravens",      color: "#241773", text: "#FFFFFF" },
  BUF: { name: "Buffalo Bills",         color: "#00338D", text: "#FFFFFF" },
  CAR: { name: "Carolina Panthers",     color: "#0085CA", text: "#FFFFFF" },
  CHI: { name: "Chicago Bears",         color: "#0B162A", text: "#FFFFFF" },
  CIN: { name: "Cincinnati Bengals",    color: "#FB4F14", text: "#000000" },
  CLE: { name: "Cleveland Browns",      color: "#311D00", text: "#FFFFFF" },
  DAL: { name: "Dallas Cowboys",        color: "#041E42", text: "#FFFFFF" },
  DEN: { name: "Denver Broncos",        color: "#FB4F14", text: "#002244" },
  DET: { name: "Detroit Lions",         color: "#0076B6", text: "#FFFFFF" },
  GB:  { name: "Green Bay Packers",     color: "#203731", text: "#FFB612" },
  HOU: { name: "Houston Texans",        color: "#03202F", text: "#FFFFFF" },
  IND: { name: "Indianapolis Colts",    color: "#002C5F", text: "#FFFFFF" },
  JAX: { name: "Jacksonville Jaguars",  color: "#101820", text: "#D7A22A" },
  KC:  { name: "Kansas City Chiefs",    color: "#E31837", text: "#FFB81C" },
  LV:  { name: "Las Vegas Raiders",     color: "#000000", text: "#A5ACAF" },
  LAC: { name: "Los Angeles Chargers",  color: "#0080C6", text: "#FFC20E" },
  LAR: { name: "Los Angeles Rams",      color: "#003594", text: "#FFA300" },
  MIA: { name: "Miami Dolphins",        color: "#008E97", text: "#FC4C02" },
  MIN: { name: "Minnesota Vikings",     color: "#4F2683", text: "#FFC62F" },
  NE:  { name: "New England Patriots",  color: "#002244", text: "#C60C30" },
  NO:  { name: "New Orleans Saints",    color: "#D3BC8D", text: "#101820" },
  NYG: { name: "New York Giants",       color: "#0B2265", text: "#A71930" },
  NYJ: { name: "New York Jets",         color: "#125740", text: "#FFFFFF" },
  PHI: { name: "Philadelphia Eagles",   color: "#004C54", text: "#A5ACAF" },
  PIT: { name: "Pittsburgh Steelers",   color: "#FFB612", text: "#101820" },
  SF:  { name: "San Francisco 49ers",   color: "#AA0000", text: "#B3995D" },
  SEA: { name: "Seattle Seahawks",      color: "#002244", text: "#69BE28" },
  TB:  { name: "Tampa Bay Buccaneers",  color: "#D50A0A", text: "#FF7900" },
  TEN: { name: "Tennessee Titans",      color: "#0C2340", text: "#4B92DB" },
  WAS: { name: "Washington Commanders", color: "#5A1414", text: "#FFB612" }
};
